# Generated by Django 3.1.6 on 2021-02-03 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
