# Generated by Django 3.1.6 on 2021-02-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_historicalstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstock',
            name='alert_amount',
        ),
        migrations.RemoveField(
            model_name='historicalstock',
            name='date',
        ),
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
