# Generated by Django 3.1.6 on 2021-02-03 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20210203_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='date',
        ),
    ]
